[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# replace STM32F429ZITx with your chip as listed in `probe-rs chip list`
# runner = "probe-rs run --connect-under-reset --chip stm32f411ceux"
runner = "probe-rs run --chip stm32f446zetx"

[build]
target = "thumbv7em-none-eabi"

[env]
DEFMT_LOG = "trace"
